{% set name = "rdkit2ase" %}
{% set version = "0.1.5" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/rdkit2ase-{{ version }}.tar.gz
  sha256: 974aad43a2f5d3c0604e9e0980c84b1714969e84728d729325debb60c81a1dc9

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - poetry-core
    - pip
  run:
    - python >={{ python_min }},<4.0.0
    - rdkit >=2024
    - ase >=3.25.0
    - networkx >=3.0.0,<4.0.0

test:
  imports:
    - rdkit2ase
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: interface between rdkit and ASE
  home: https://github.com/zincware/rdkit2ase
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
