{% set name = "rdkit2ase" %}
{% set version = "0.1.8" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/rdkit2ase-{{ version }}.tar.gz
  sha256: 7e4ed9e909261aa48faabb9c848dbb67f45edc5632869ed100575741c6c363e6

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }},<4.0.0
    - rdkit >=2024
    - ase >=3.25.0
    - networkx >=3.4.2

test:
  imports:
    - rdkit2ase
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: interface between rdkit and ASE
  home: https://github.com/zincware/rdkit2ase
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
